name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Generate Sitemap
        run: npm run generate-sitemap

      - name: Deploy
        # Add your deployment steps here, e.g., using GitHub Pages or another platform
